Add dialog before drafting email, if not all progress items are completed.
GoogleChrome/chromium-dashboard pull request #1796
Opened 2022-03-17 17:22 UTC by dlaliberte

This adds a dialog to the chromedash-process-overview component based on the design in https://docs.google.com/document/d/1eh8uT_DiJncvUi5ZZicLBkX06nepD8Lza8XR40yI08c/edit?resourcekey=0-IpKO8GjpLX-Qg9_Is-UHUw

2022-03-18 01:18 UTC, jrobbins requested changes
Overall this looks good.   I have some wording and CSS comments.

I think the main thing blocking this from landing is that I need to go through the list of progress items and narrow them down and make sure that they are all actionable.  I'll try to get that PR sent tomorrow.

2022-03-18 01:18 UTC, jrobbins commented on static/elements/chromedash-process-overview.js
> +      <a href="${this.pendingItems.continueUrl}" target="_blank">Continue to Draft Email</a>
This button label is kind of long.
How about just: "Continue" or "Proceed"?

Also, this seems like a case where the button should have a border, but not be filled in to look like the primary button.    And, the buttons are crowded too close together.

Try:
margin: var(--content-padding);
border: var(--default-border);
border-color: var(--primary-border-background);
padding: 4px 16px;
border-radius: var(--border-radius);

You could just do that here in this component, or if you are feel like diving into our CSS you could add some "outlined button" variables to theme.css and then define a new button CSS class in shared.scss.

2022-03-18 14:38 UTC, dlaliberte commented on static/elements/chromedash-process-overview.js
> +    <chromedash-dialog heading="Progress Steps Missing">
done

2022-03-18 14:39 UTC, dlaliberte commented
Here is a screenshot with the title and button style changes.

![image](https://user-images.githubusercontent.com/570125/159023565-95f40998-a182-4413-a38e-a2e874ea1810.png)

2022-03-18 16:27 UTC, jrobbins commented
This all looks good.  I just need to revisit the progress detectors before we merge and deploy this.

2022-03-20 17:16 UTC, dlaliberte commented
I'm thinking the dialog is lacking a bit of useful context.  Maybe we should add a sentence at the top, something like:  "Before proceeding to Draft Intent to Experiment email, note that there are one or more fields missing:".  That way, the reason for the dialog, and the meaning of the "Edit fields" and "Proceed" buttons becomes clear.

I also see there is a bit of extra whitespace below the buttons.  I'll check that out.

2022-03-20 17:19 UTC, dlaliberte commented
Another thing to note is that the "One LGTM on Intent to Experiment" won't be possible without having first sent out the email, so this field will always be missing.     Should we skip all items after the "...email" item?

2022-03-20 18:53 UTC, jrobbins commented
We could omit everything after the "... email" progress item.  Or, we could add a new boolean to each progress item named something like is_intent_prerequisite.

2022-03-22 15:57 UTC, jpmedley commented
Sorry I didn't find this earlier. What does this do with milestone fields?

2022-03-23 19:12 UTC, closed without merging