Add APIOwner models to store the API Owner file
GoogleChrome/chromium-dashboard pull request #2093
Opened 2022-08-10 00:16 UTC by KyleJu

Fix #2084

2022-08-10 00:31 UTC, jrobbins requested changes
I have a few comments to consider.

2022-08-10 00:31 UTC, jrobbins commented on internals/models.py
> +  url = ndb.StringProperty()
Maybe make url and raw_content required?
I generally don't make a lot of fields required, but in this case the URL is like the key, and the raw_content is pretty much the point of the whole entity.

2022-08-10 00:31 UTC, jrobbins commented on internals/models.py
> +class APIOwner(DictModel):
It would be good to generalize this a bit to other OWNERS files as well.  E.g., name it something like `OwnersFile`.

2022-08-10 00:31 UTC, jrobbins commented on internals/models.py
> +    ndb.delete_multi(self.query().fetch(keys_only=True))
Deleting all other instances works so long as the API Owners file is the only OWNERS file that we have, but in the future we might have other approvals that parse other OWNERS files from different URLs.   Deleting unneeded entities could still be done like:
`ndb.delete_multi(self.query(OwnersFile.url == url).fetch(keys_only=True))`

2022-08-10 22:13 UTC, jrobbins approved these changes

2022-08-10 22:15 UTC, KyleJu commented
https://github.com/GoogleChrome/chromium-dashboard/runs/7771977381?check_suite_focus=true - the CI is hanging on the test. Let me dig into it

2022-08-11 01:37 UTC, KyleJu commented
Tests also hanging locally. The test setup needs to be tweaked

2022-08-11 20:41 UTC, merged