Add extra help for feature name and summary.
GoogleChrome/chromium-dashboard pull request #2149
Opened 2022-08-19 18:55 UTC by dlaliberte

This PR adds the extra_help attribute for a few of the feature form fields based on the [EditingHelp](https://github.com/GoogleChrome/chromium-dashboard/wiki/EditingHelp#feature-name) document.

Note that, for help_text and extra_help, the current style which attempts to remove the margin-top and margin-bottom for the first and last child of those text blocks will fail to do what I expected in the case that there is text not enclosed in an element.  So unless we can find an alternative way to remove the extra margin, we have to unsure that text with multiple blocks should wrap each block with `<p>...</p>` or whatever.

2022-08-19 18:58 UTC, dlaliberte commented
Here is what it looks like with these two extra_help blocks displayed:

https://screenshot.googleplex.com/4hrvGVtGXoRQWgY

2022-08-19 19:30 UTC, jpmedley requested changes
I went ahead and tweaked a few things, so I don't need to remember to fix them later.

2022-08-19 19:30 UTC, jpmedley commented on static/elements/form-field-specs.js
> +      <li>Do not include markup or markdown.</li>
```suggestion
      <li>Do not include markup or markdown because they will not be rendered.</li>
```

2022-08-19 19:30 UTC, jpmedley commented on static/elements/form-field-specs.js
> +      <li>CSS Flexbox: New intrinsic size algorithm</li>
```suggestion
      <li>CSS Flexbox: intrinsic size algorithm</li>
```

2022-08-19 19:30 UTC, jpmedley commented on static/elements/form-field-specs.js
> +    Note: This text communicates with more than just the rest of Chromium development. It's the part most visible to external readers and is used as the basis for the text in the beta release posts.
```suggestion
    Note: This text communicates with more than just the rest of Chromium development. It's the part most visible to external readers and is used in the beta release announcement, enterprise release notes, and other commuinications.
```

2022-08-19 19:30 UTC, jpmedley commented on static/elements/form-field-specs.js
> +      <li>Do not use markup or markdown.</li>
```suggestion
      <li>Do not use markup or markdown because they will not be rendered.</li>
```

2022-08-19 19:30 UTC, jpmedley commented on static/elements/form-field-specs.js
> +      <li>Do not use hard or soft returns.</li>
```suggestion
      <li>Do not use hard or soft returns  because they will not be rendered.</li>
```

2022-08-19 23:57 UTC, dlaliberte commented on static/elements/form-field-specs.js
> +      <li>Do not include markup or markdown.</li>
done

2022-08-19 23:58 UTC, dlaliberte commented on static/elements/form-field-specs.js
> +      <li>CSS Flexbox: New intrinsic size algorithm</li>
done

2022-08-19 23:59 UTC, dlaliberte commented on static/elements/form-field-specs.js
> +    Note: This text communicates with more than just the rest of Chromium development. It's the part most visible to external readers and is used as the basis for the text in the beta release posts.
done

2022-08-20 00:00 UTC, dlaliberte commented on static/elements/form-field-specs.js
> +      <li>Do not use markup or markdown.</li>
done

2022-08-20 00:00 UTC, dlaliberte commented on static/elements/form-field-specs.js
> +      <li>Do not use hard or soft returns.</li>
done

2022-08-22 14:49 UTC, jpmedley approved these changes

2022-08-22 14:50 UTC, jpmedley commented
Does @jrobbins need to approve this before we merge?

2022-08-22 16:11 UTC, jrobbins approved these changes

2022-08-22 20:35 UTC, merged