Create Redis staging setup
GoogleChrome/chromium-dashboard pull request #2211
Opened 2022-09-07 06:49 UTC by KyleJu

Taken from #2146. Create Redis staging setup using the [set-up instructions](https://docs.google.com/document/d/1hV5MTrGjtKy5kyyk2983kJz3POUWSOBbH-t-qBRQ7Ns/edit?usp=sharing&resourcekey=0-hdThpHi-WIM-48sl4EfO6Q).

Tested in #2146

2022-09-07 22:48 UTC, jrobbins requested changes

2022-09-07 22:48 UTC, jrobbins commented on scripts/deploy_site.sh
> +  $BASEDIR/../app.staging.yaml  \
With this change, how would we deploy to prod?
I think we need a conditional in here somewhere, or we need to specify a command-line argument with the name of the yaml file to deploy (or just the 'staging' or 'prod' part of it).

2022-09-12 20:18 UTC, jrobbins approved these changes

2022-09-12 20:49 UTC, jrobbins commented
It looks like you added a ton of files to this PR.

2022-09-12 20:51 UTC, KyleJu commented
> It looks like you added a ton of files to this PR.

I merged two other PRs into this PR. Should I have done the other way around? (Merge to main one at a time)

2022-09-12 20:56 UTC, KyleJu commented
The files being merged are reviewed in https://github.com/GoogleChrome/chromium-dashboard/pull/2212. Everything looks good so I will merge this PR to main

2022-09-12 20:56 UTC, merged

2022-09-12 21:09 UTC, jrobbins commented
Ah, OK.
I think the best way to do it would have been:
1. Merge your other PRs into main on GitHub.com
2. git checkout main
3. git pull
4. git checkout redis-setup
5. git merge main
6. If there are any conflicts resolve them and commit, but in this case I don't think there would be any
7. git push

2022-09-12 21:24 UTC, KyleJu commented
> Ah, OK. I think the best way to do it would have been:
> 
> 1. Merge your other PRs into main on GitHub.com
> 2. git checkout main
> 3. git pull
> 4. git checkout redis-setup
> 5. git merge main
> 6. If there are any conflicts resolve them and commit, but in this case I don't think there would be any
> 7. git push

Since the three PRs are parent/child, we can probably execute your command from the parent PR to children PRs, but yea merging to main one at a time is a better option!