Crate an Activity Page
GoogleChrome/chromium-dashboard pull request #2925
Opened 2023-04-19 22:28 UTC by KyleJu

#2831. Create a standalone activity page that shows all activities and comments associated with a feature.

2023-04-19 23:09 UTC, KyleJu commented
A screenshot
<img width="1648" alt="Screenshot 2023-04-19 at 3 16 26 PM" src="https://user-images.githubusercontent.com/8611520/233218623-78d043fa-d5e8-40f2-8512-5ee948a8c686.png">

2023-04-20 15:34 UTC, jrobbins requested changes

2023-04-20 15:34 UTC, jrobbins commented on client-src/elements/chromedash-activity-page.js
> +        .feature=${this.featureId}
Isn't the property name now `featureId`?

2023-04-21 19:10 UTC, KyleJu commented on main.py
> +  Route('/activity/<int:feature_id>'),
That is a better path!

2023-04-21 19:11 UTC, KyleJu commented on client-src/elements/chromedash-feature-detail.js
> +            .feature=${this.feature.id}
Yup I will send a follow-up PR

2023-04-21 20:07 UTC, jrobbins approved these changes

2023-04-21 20:08 UTC, merged