Add Blink>HID
GoogleChrome/chromium-dashboard pull request #4371
Opened 2024-09-17 07:21 UTC by beaufortfrancois

This PR adds missing Blink component for WebHID as it's needed for https://chromestatus.com/feature/5077348995825664

2024-09-17 17:20 UTC, jrobbins approved these changes

2024-09-17 17:28 UTC, jrobbins commented
Actually, "Blink>HID" is already on line 76.  So, I am not sure that this is needed.  Testing it on the live site, I find that "Blink>HID" is already offered in the datalist UI element for choosing the blink component.

2024-09-17 17:29 UTC, jrobbins requested changes
Blink>HID is already on line 76.

2024-09-17 17:30 UTC, jrobbins commented
Did you mean to spell it as "Blink>WebHID"?

2024-09-18 06:04 UTC, beaufortfrancois commented
I was wrong. Sorry for that.

2024-09-18 06:04 UTC, closed without merging